default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ubuntu
  password: password

development:
  <<: *default
  database: workspace_development

test:
  <<: *default
  database: workspace_test

production:
  <<: *default
  database: workspace_production
  username: workspace
  password: <%= ENV['WORKSPACE_DATABASE_PASSWORD'] %>
